
exporter_port: 9158 # Port on which prometheus can call this exporter to get metrics
log_level: info
json_data_urls:
  - url: http://stubonweb.herokuapp.com/ # Base url to get json data used for fetching metric values
    app: kong_cluster_1
    env: developement
    kind: kong_cluster # All metrics defined in kind "kong_cluster" will be executed for this endpoint
  - url: http://stubonweb.herokuapp.com/
    app: kong_cluster_1
    env: production
    kind: kong_cluster
  - url: http://stubonweb.herokuapp.com/
    app: kong_cluster_2
    env: developement
    kind: kong_cluster
  - url: http://stubonweb.herokuapp.com/
    app: kong_cluster_2
    env: production
    kind: kong_cluster

metrics:
  - kind: kong_cluster
    prefix: kong_cluster # All metric names will be prefixed with this value
    jsonpath: kong-cluster-status # path to json
    metric:
      - name: total_nodes # Final metric name will be kong_cluster_total_nodes
        description: Total number of nodes in kong cluster
        path: $.total
      - name: alive_nodes # Final metric name will be kong_cluster_alive_nodes
        description: Number of live nodes in kong cluster
        path: count($.data[@.status is "alive"])
